services:
  next:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: pnpm dev
    container_name: next-dev 
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=QWERTY123
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres-dev

# docker run --name redis -d -p 6379:6379 redis redis-server --requirepass "SUPER_SECRET_PASSWORD"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass "QWERTY123"
    container_name: redis-dev

volumes:
  postgres_data:
  redis_data:
