services:
  next:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      # - /app/node_modules
      # - /app/.next
    environment:
      - NODE_ENV=development
    command: pnpm dev
    container_name: next-dev 
    depends_on:
      - postgres
      - redis
    networks:
      - my_network

  postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=QWERTY123
      - POSTGRES_DB=next_starter
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres-dev
    networks:
      - my_network

# docker run --name redis -d -p 6379:6379 redis redis-server --requirepass "SUPER_SECRET_PASSWORD"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass "QWERTY123"
    container_name: redis-dev
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=mhpsy@proton.me
      - PGADMIN_DEFAULT_PASSWORD=QWERTY123
      - PGADMIN_LISTEN_PORT=80
    container_name: pgadmin-dev
    volumes:
      - pgadmin_data:/pgadmin
    depends_on:
      - postgres
    networks:
      - my_network

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  my_network: