
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
